package exception.Throw;

public class throw2 {
    public static void main(String[] args) {

    }

    public void f1() throws ArithmeticException{
        int n1 =10,n2 =0;
        int res = n1/n2;
    }
}


